### ISSUE TITLE
Assignment #1 tasks

### ISSUE THREAD

**Issue by soenAnt** [v2thegreat/COMP-472-AI#2]
**Task 0**
- [x] - remove document identifier, topic label
- [x] - split data into training/evaluation (80/20)

**Task 1**
- [x] - plot distribution of the number of instances in each class

**Task 2**
- [x] - run Naive Bayer model
- [x] - run Base-DT model
- [x] - run best-DT model

**Task 3**
- [x] - for each mode, write code to generate output file containing the output classification & performance. (Should be named [model name]-[dataset]) (3 files total)
- [x] - each file should contain, row number of instances, followed by a comma, followed by index of the predicted class of that instance
- [x] - each file should contain a plot the confusion matrix
- [x] - each file should contain the precision, recall, and f1-measure for each class
- [x] - each file should contain the accuracy

**Task 4**
- [x] - find the misclassified documents and comment on why we think they were hard to classify. 

——

**Deliverables:**  
- [x] - code & output files (including a readme.md with instructions on how to run the experiments).
- [x] - demo (need to prepare an 8-minutes presentation to analyze & compare performance of our models).

**The presentation should contain:**
- [x] - analysis of the initial dataset (if we notice something that can impact the performance of some models, we should explain it)
- [x] - Analysis of the results of the models (comparing each model with other models, not just demonstrate numbers, but also analyze why they are) (tables + graphs) 
- [x] - description of the responsibilities & contributions of each team member
- [x] - our code should work with any dataset provided by TA during the demo to run
